function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        BOTZIE_CATEGORY: 'Botzie',
        BOTZIE_ADVANCED_CATEGORY: 'Botzie Advanced',
        BOTZIE_ADVANCED_LABEL: 'Per-motor speed (0-255)',
        BOTZIE_SETUP: 'setup Botzie',
        BOTZIE_CONNECT_BT: 'connect Botzie Bluetooth %1 name %2',
        BOTZIE_BT_CLASSIC: 'classic',
        BOTZIE_BT_BLE: 'BLE',
        BOTZIE_CONNECT_WIFI: 'connect Botzie WiFi %1 SSID %2 password %3',
        BOTZIE_WIFI_STA: 'join network',
        BOTZIE_WIFI_AP: 'hotspot (AP)',
        BOTZIE_DISCONNECT: 'disconnect Botzie',
        BOTZIE_MOVE_FORWARD: 'move forward',
        BOTZIE_MOVE_BACKWARD: 'move backward',
        BOTZIE_TURN_LEFT: 'turn left',
        BOTZIE_TURN_RIGHT: 'turn right',
        BOTZIE_STOP: 'stop Botzie',
        BOTZIE_ROTATE_CW: 'rotate clockwise',
        BOTZIE_ROTATE_CCW: 'rotate anticlockwise',
        BOTZIE_MOVE_DIR_SPEED: 'move %1 at speed %2',
        BOTZIE_SET_LR_SPEED: 'set left motor speed %1 right motor speed %2',
        BOTZIE_SET_SPEED_PCT: 'set speed %1 %',
        BOTZIE_INCREASE_SPEED: 'increase speed by %1',
        BOTZIE_DECREASE_SPEED: 'decrease speed by %1',
        BOTZIE_SPEED_VALUE: 'speed value',
        BOTZIE_DISTANCE_CM: 'distance in cm',
        BOTZIE_OBSTACLE: 'obstacle detected within %1 cm?',
        BOTZIE_LINE_LEFT: 'line sensor left',
        BOTZIE_LINE_RIGHT: 'line sensor right',
        BOTZIE_SEND_TERMINAL: 'send to terminal %1',
        BOTZIE_SEND_GRAPH: 'send graph %1 value %2',
        BOTZIE_COMMAND_IS: 'when Botzie command is %1',
        BOTZIE_ACTION_COMMAND: 'Botzie action %1 command %2',
        BOTZIE_RESUME: 'resume',
        BOTZIE_RECEIVED_COMMAND: 'received command',
        BOTZIE_BEEP: 'beep buzzer for %1 seconds'
    });

    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        BOTZIE_CATEGORY: 'Botzie',
        BOTZIE_ADVANCED_CATEGORY: 'Botzie 高级',
        BOTZIE_ADVANCED_LABEL: '单电机速度 (0-255)',
        BOTZIE_SETUP: '初始化 Botzie',
        BOTZIE_CONNECT_BT: '连接 Botzie 蓝牙 %1 名称 %2',
        BOTZIE_BT_CLASSIC: '经典蓝牙',
        BOTZIE_BT_BLE: 'BLE',
        BOTZIE_CONNECT_WIFI: '连接 Botzie WiFi %1 SSID %2 密码 %3',
        BOTZIE_WIFI_STA: '加入网络',
        BOTZIE_WIFI_AP: '热点 (AP)',
        BOTZIE_DISCONNECT: '断开 Botzie 连接',
        BOTZIE_MOVE_FORWARD: '前进',
        BOTZIE_MOVE_BACKWARD: '后退',
        BOTZIE_TURN_LEFT: '左转',
        BOTZIE_TURN_RIGHT: '右转',
        BOTZIE_STOP: '停止 Botzie',
        BOTZIE_ROTATE_CW: '顺时针旋转',
        BOTZIE_ROTATE_CCW: '逆时针旋转',
        BOTZIE_MOVE_DIR_SPEED: '向 %1 移动 速度 %2',
        BOTZIE_SET_LR_SPEED: '左电机速度 %1 右电机速度 %2',
        BOTZIE_SET_SPEED_PCT: '设置速度 %1 %',
        BOTZIE_INCREASE_SPEED: '加速 %1',
        BOTZIE_DECREASE_SPEED: '减速 %1',
        BOTZIE_SPEED_VALUE: '速度值',
        BOTZIE_DISTANCE_CM: '距离 cm',
        BOTZIE_OBSTACLE: '障碍在 %1 cm 内?',
        BOTZIE_LINE_LEFT: '左循迹传感器',
        BOTZIE_LINE_RIGHT: '右循迹传感器',
        BOTZIE_SEND_TERMINAL: '发送到终端 %1',
        BOTZIE_SEND_GRAPH: '发送图表 %1 值 %2',
        BOTZIE_COMMAND_IS: '当 Botzie 命令是 %1',
        BOTZIE_ACTION_COMMAND: 'Botzie 动作 %1 命令 %2',
        BOTZIE_RESUME: '继续',
        BOTZIE_RECEIVED_COMMAND: '收到的命令',
        BOTZIE_BEEP: '蜂鸣器响 %1 秒'
    });

    return Blockly;
}

module.exports = addMsg;
