/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
function addMsg (Blockly) {
    Object.assign(Blockly.ScratchMsgs.locales.en, {
        ESP32CAM_CATEGORY: 'ESP32-CAM',
        ESP32CAM_INIT: 'set camera as %1',
        ESP32CAM_SOURCE_CAMERA: 'ESP32-CAM',
        ESP32CAM_SOURCE_WEB: 'web stream',
        ESP32CAM_STREAM_URL: 'camera stream URL %1',
        ESP32CAM_WIFI: 'start WiFi %1 SSID %2 password %3',
        ESP32CAM_WIFI_STA: 'join network',
        ESP32CAM_WIFI_AP: 'hotspot (AP)',
        ESP32CAM_RESOLUTION: 'set camera resolution to %1',
        ESP32CAM_FRAME_RATE: 'set camera frame rate to %1 fps',
        ESP32CAM_JPEG_QUALITY: 'set camera JPEG quality to %1 %',
        ESP32CAM_ROTATION: 'rotate camera stream by %1',
        ESP32CAM_FLIP: 'flip camera %1',
        ESP32CAM_FLIP_NONE: 'none',
        ESP32CAM_FLIP_HORIZONTAL: 'horizontal',
        ESP32CAM_FLIP_VERTICAL: 'vertical',
        ESP32CAM_FLIP_BOTH: 'both',
        ESP32CAM_LED_ON: 'camera LED on',
        ESP32CAM_LED_OFF: 'camera LED off',
        ESP32CAM_STREAM_WEB: 'start web video stream',
        ESP32CAM_HANDLE_CLIENT: 'handle web stream requests',
        ESP32CAM_SURVEILLANCE: 'start surveillance mode',
        ESP32CAM_FACE_MODE: 'start face detection mode (Vision Core app)',
        ESP32CAM_COLOR_MODE: 'start color recognition mode (Vision Core app)',
        ESP32CAM_FINGER_MODE: 'start finger detection mode (Vision Core app)',
        ESP32CAM_QR_MODE: 'start QR detection mode (Vision Core app)',
        ESP32CAM_EMOTION_MODE: 'start emotion detection mode (Vision Core app)',
        ESP32CAM_OBJECT_MODE: 'start object follow mode %1 (Vision Core app)',
        ESP32CAM_LINE_BLACK: 'process black line follow and send BL to kit',
        ESP32CAM_LINE_WHITE: 'process white line follow and send WL to kit',
        ESP32CAM_SEND_STEERING: 'send BL steering value %1 to kit',
        ESP32CAM_SEND_QR: 'send QR command %1 to kit',
        ESP32CAM_SEND_QR_RAW: 'send QR raw text %1 to kit',
        ESP32CAM_SEND_SC: 'send surveillance command %1 to kit',
        ESP32CAM_SEND_CT: 'send color tracking %1 found %2 errX %3 errY %4 to kit',
        ESP32CAM_SEND_OBJECT: 'send object %1 at center %2 width %3 to kit',
        ESP32CAM_MODE_BASIC: 'basic',
        ESP32CAM_MODE_INTER: 'intermediate',
        ESP32CAM_MODE_ADV: 'advanced',
        ESP32CAM_QR_FWD: 'forward',
        ESP32CAM_QR_BWD: 'backward',
        ESP32CAM_QR_LEFT: 'left',
        ESP32CAM_QR_RIGHT: 'right',
        ESP32CAM_QR_UTURN: 'U Turn',
        ESP32CAM_QR_STOP: 'stop'
    });
    Object.assign(Blockly.ScratchMsgs.locales['zh-cn'], {
        ESP32CAM_CATEGORY: 'ESP32-CAM 摄像头',
        ESP32CAM_INIT: '设置摄像头为 %1',
        ESP32CAM_SOURCE_CAMERA: 'ESP32-CAM',
        ESP32CAM_SOURCE_WEB: '网页视频流',
        ESP32CAM_STREAM_URL: '摄像头视频流地址 %1',
        ESP32CAM_WIFI: '启动 WiFi %1 名称 %2 密码 %3',
        ESP32CAM_WIFI_STA: '加入网络',
        ESP32CAM_WIFI_AP: '热点 (AP)',
        ESP32CAM_RESOLUTION: '设置摄像头分辨率为 %1',
        ESP32CAM_FRAME_RATE: '设置摄像头帧率为 %1 fps',
        ESP32CAM_JPEG_QUALITY: '设置摄像头 JPEG 质量为 %1 %',
        ESP32CAM_ROTATION: '旋转摄像头画面 %1',
        ESP32CAM_FLIP: '翻转摄像头 %1',
        ESP32CAM_FLIP_NONE: '不翻转',
        ESP32CAM_FLIP_HORIZONTAL: '水平',
        ESP32CAM_FLIP_VERTICAL: '垂直',
        ESP32CAM_FLIP_BOTH: '水平和垂直',
        ESP32CAM_LED_ON: '摄像头 LED 开',
        ESP32CAM_LED_OFF: '摄像头 LED 关',
        ESP32CAM_STREAM_WEB: '启动网页视频流',
        ESP32CAM_HANDLE_CLIENT: '处理网页视频请求',
        ESP32CAM_SURVEILLANCE: '启动监控模式',
        ESP32CAM_FACE_MODE: '启动人脸检测模式 (Vision Core)',
        ESP32CAM_COLOR_MODE: '启动颜色识别模式 (Vision Core)',
        ESP32CAM_FINGER_MODE: '启动手指检测模式 (Vision Core)',
        ESP32CAM_QR_MODE: '启动 QR 检测模式 (Vision Core)',
        ESP32CAM_EMOTION_MODE: '启动情绪检测模式 (Vision Core)',
        ESP32CAM_OBJECT_MODE: '启动物体跟随模式 %1 (Vision Core)',
        ESP32CAM_LINE_BLACK: '处理黑线巡线并发送 BL 到小车',
        ESP32CAM_LINE_WHITE: '处理白线巡线并发送 WL 到小车',
        ESP32CAM_SEND_STEERING: '发送 BL 转向值 %1 到小车',
        ESP32CAM_SEND_QR: '发送 QR 指令 %1 到小车',
        ESP32CAM_SEND_QR_RAW: '发送 QR 原始文本 %1 到小车',
        ESP32CAM_SEND_SC: '发送监控指令 %1 到小车',
        ESP32CAM_SEND_CT: '发送颜色跟踪 %1 发现 %2 误差X %3 误差Y %4 到小车',
        ESP32CAM_SEND_OBJECT: '发送物体 %1 中心 %2 宽度 %3 到小车',
        ESP32CAM_MODE_BASIC: '基础',
        ESP32CAM_MODE_INTER: '中级',
        ESP32CAM_MODE_ADV: '高级',
        ESP32CAM_QR_FWD: '前进',
        ESP32CAM_QR_BWD: '后退',
        ESP32CAM_QR_LEFT: '左转',
        ESP32CAM_QR_RIGHT: '右转',
        ESP32CAM_QR_UTURN: '掉头',
        ESP32CAM_QR_STOP: '停止'
    });
    return Blockly;
}

exports = addMsg;
